// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// build_hashes
void build_hashes(CharacterVector outer_keys);
RcppExport SEXP tnseq_build_hashes(SEXP outer_keysSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type outer_keys(outer_keysSEXP);
    build_hashes(outer_keys);
    return R_NilValue;
END_RCPP
}
// erase_hashes
void erase_hashes(CharacterVector outer_keys);
RcppExport SEXP tnseq_erase_hashes(SEXP outer_keysSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type outer_keys(outer_keysSEXP);
    erase_hashes(outer_keys);
    return R_NilValue;
END_RCPP
}
// add_keys
void add_keys(std::string outer, CharacterVector keys);
RcppExport SEXP tnseq_add_keys(SEXP outerSEXP, SEXP keysSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type outer(outerSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type keys(keysSEXP);
    add_keys(outer, keys);
    return R_NilValue;
END_RCPP
}
// get_values
NumericVector get_values(std::string outer, CharacterVector keys);
RcppExport SEXP tnseq_get_values(SEXP outerSEXP, SEXP keysSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type outer(outerSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type keys(keysSEXP);
    __result = Rcpp::wrap(get_values(outer, keys));
    return __result;
END_RCPP
}
// write_hash_to_file
int write_hash_to_file(std::string outer_key, std::string filename);
RcppExport SEXP tnseq_write_hash_to_file(SEXP outer_keySEXP, SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type outer_key(outer_keySEXP);
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    __result = Rcpp::wrap(write_hash_to_file(outer_key, filename));
    return __result;
END_RCPP
}
